{
  "openapi": "3.0.1",
  "info": {
    "title": "Var Tool Api API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Local"
    },
    {
      "url": "https://developmentapi.ienterprise.info/var",
      "description": "Dev"
    },
    {
      "url": "https://stagingapi.ienterprise.com/var",
      "description": "Staging"
    }
  ],
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "paths": {
    "/pre-load-device-data/import": {
      "post": {
        "tags": [
          "inventory-api"
        ],
        "summary": "Create one or more new Inventory Preload records(mobile and computer) using CSV, for now we support only mobile devices",
        "operationId": "importData",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "required": [
                  "file"
                ],
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseInventoryImportResponse"
                }
              }
            }
          },
          "401": {
            "description": "Returns unauthorized/forbidden response code"
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "messageCodes": [
                    "unknown.error"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "/health": {
      "get": {
        "tags": [
          "health-api"
        ],
        "operationId": "checkHealth",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "401": {
            "description": "Returns unauthorized/forbidden response code"
          },
          "500": {
            "description": "returns error response(success=false,body=null) with messageCodes",
            "content": {
              "application/json": {
                "example": {
                  "success": false,
                  "messageCodes": [
                    "unknown.error"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiResponseInventoryImportResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "messageCodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "body": {
            "$ref": "#/components/schemas/InventoryImportResponse"
          }
        }
      },
      "DeviceDataField": {
        "type": "object",
        "properties": {
          "value": {
            "type": "string"
          },
          "valid": {
            "type": "boolean"
          },
          "errorCode": {
            "type": "string"
          },
          "additionalErrorInfo": {
            "type": "string"
          }
        }
      },
      "DeviceDataRecord": {
        "type": "object",
        "properties": {
          "rowNumber": {
            "type": "integer",
            "format": "int32"
          },
          "valid": {
            "type": "boolean"
          },
          "errorCode": {
            "type": "string"
          },
          "serialNumber": {
            "$ref": "#/components/schemas/DeviceDataField"
          },
          "deviceType": {
            "$ref": "#/components/schemas/DeviceDataField"
          },
          "userName": {
            "$ref": "#/components/schemas/DeviceDataField"
          },
          "emailAddress": {
            "$ref": "#/components/schemas/DeviceDataField"
          },
          "eaEnv": {
            "$ref": "#/components/schemas/DeviceDataField"
          },
          "eaStore": {
            "$ref": "#/components/schemas/DeviceDataField"
          },
          "eaUseCase": {
            "$ref": "#/components/schemas/DeviceDataField"
          }
        }
      },
      "InventoryImportResponse": {
        "type": "object",
        "properties": {
          "records": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/DeviceDataRecord"
            }
          },
          "hasErrors": {
            "type": "boolean"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
